import os 
from dotenv import load_dotenv

load_dotenv()

ELASTICSEARCH_URL = os.getenv('ELASTICSEARCH_URL')
ELASTICSEARCH_ID = os.getenv('ELASTICSEARCH_ID')
ELASTICSEARCH_PW = os.getenv('ELASTICSEARCH_PW')
ELASTICSEARCH_AUTH = (ELASTICSEARCH_ID, ELASTICSEARCH_PW)